<?php

namespace Database\Seeders;

use App\Core\Domain\Shared\Enums\CharacterCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharacterSeeder extends Seeder
{
    public function run(): void
    {
        $characters = [
            // Esporte
            ['name' => 'Pelé', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Neymar', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Ronaldinho Gaúcho', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Romário', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Cristiano Ronaldo', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Lionel Messi', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Vini Jr.', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Diego Maradona', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Zinedine Zidane', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Kylian Mbappé', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Ronaldo Fenômeno', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Kaká', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Zico', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Garrincha', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Cafu', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Marta', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'David Beckham', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Tyson Fury', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Khabib Nurmagomedov', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Rivaldo', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Oscar Schmidt', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Michael Jordan', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'LeBron James', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Anderson Silva', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'José Aldo', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Charles do Bronx', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Conor McGregor', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Mike Tyson', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Muhammad Ali', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Popó', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Gustavo Kuerten', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Rafael Nadal', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Ayrton Senna', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Nelson Piquet', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Lewis Hamilton', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Gabriel Medina', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Ítalo Ferreira', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Daiane dos Santos', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'César Cielo', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Rebeca Andrade', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Galvão Bueno', 'category_id' => CharacterCategory::SPORT],
            ['name' => 'Cléber Machado', 'category_id' => CharacterCategory::SPORT],

            // Mídias sociais
            ['name' => 'Felipe Neto', 'category_id' => CharacterCategory::SOCIAL_MEDIA],
            ['name' => 'Whindersson Nunes', 'category_id' => CharacterCategory::SOCIAL_MEDIA],
            ['name' => 'Casimiro', 'category_id' => CharacterCategory::SOCIAL_MEDIA],
            ['name' => 'Carlinhos Maia', 'category_id' => CharacterCategory::SOCIAL_MEDIA],
            ['name' => 'Virgínia Fonseca', 'category_id' => CharacterCategory::SOCIAL_MEDIA],
            ['name' => 'Bruna Marquezine', 'category_id' => CharacterCategory::SOCIAL_MEDIA],
            ['name' => 'Gaules', 'category_id' => CharacterCategory::SOCIAL_MEDIA],

            // Política e exército
            ['name' => 'Getúlio Vargas', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Jair Bolsonaro', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Luiz Inácio Lula da Silva', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Fernando Henrique Cardoso', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Tancredo Neves', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Dilma Rousseff', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Dom Pedro I', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Tiradentes', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Zumbi dos Palmares', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Princesa Isabel', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Napoleão Bonaparte', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Dom Pedro II', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Rei Charles III', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Rainha Elizabeth II', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Duque de Caxias', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Sobral Pinto', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],

            // Religião
            ['name' => 'Papa Francisco', 'category_id' => CharacterCategory::RELIGION],
            ['name' => 'Padre Marcelo Rossi', 'category_id' => CharacterCategory::RELIGION],
            ['name' => 'Edir Macedo', 'category_id' => CharacterCategory::RELIGION],
            ['name' => 'Silas Malafaia', 'category_id' => CharacterCategory::RELIGION],
            ['name' => 'Dalai Lama', 'category_id' => CharacterCategory::RELIGION],

            // Finanças
            ['name' => 'Abilio Diniz', 'category_id' => CharacterCategory::FINANCE],
            ['name' => 'Luiz Barsi', 'category_id' => CharacterCategory::FINANCE],
            ['name' => 'Warren Buffett', 'category_id' => CharacterCategory::FINANCE],

            // Ciência e tecnologia
            ['name' => 'Albert Einstein', 'category_id' => CharacterCategory::SCIENCE_AND_TECHNOLOGY],
            ['name' => 'Oswaldo Cruz', 'category_id' => CharacterCategory::SCIENCE_AND_TECHNOLOGY],
            ['name' => 'Marie Curie', 'category_id' => CharacterCategory::SCIENCE_AND_TECHNOLOGY],
            ['name' => 'Elon Musk', 'category_id' => CharacterCategory::SCIENCE_AND_TECHNOLOGY],
            ['name' => 'Steve Jobs', 'category_id' => CharacterCategory::SCIENCE_AND_TECHNOLOGY],
            ['name' => 'Mark Zuckerberg', 'category_id' => CharacterCategory::SCIENCE_AND_TECHNOLOGY],
            ['name' => 'Bill Gates', 'category_id' => CharacterCategory::SCIENCE_AND_TECHNOLOGY],
            ['name' => 'Marcos Pontes', 'category_id' => CharacterCategory::SCIENCE_AND_TECHNOLOGY],
            ['name' => 'Drauzio Varella', 'category_id' => CharacterCategory::SCIENCE_AND_TECHNOLOGY],

            // Televisão
            ['name' => 'Erick Jacquin', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'Paola Carosella', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'Henrique Fogaça', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'Silvio Santos', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'Faustão', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'Luciano Huck', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'Xuxa', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'Ana Maria Braga', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'Hebe Camargo', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'William Bonner', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'Fátima Bernardes', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'José Luiz Datena', 'category_id' => CharacterCategory::TELEVISION],
            ['name' => 'Mauricio Maia', 'category_id' => CharacterCategory::TELEVISION],

            // Mundo fictício
            ['name' => 'Zé Pequeno', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Capitão Nascimento', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Seu Madruga', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Chaves', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Mônica', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Cebolinha', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Bob Esponja', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Mickey Mouse', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Homer Simpson', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Harry Potter', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Naruto Uzumaki', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Batman', 'category_id' => CharacterCategory::FICTION],

            // Ficção — super-heróis / quadrinhos
            ['name' => 'Superman', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Homem-Aranha', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Mulher-Maravilha', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Hulk', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Homem de Ferro', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Capitão América', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Thor', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Wolverine', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Deadpool', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Coringa', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Flash', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Aquaman', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Thanos', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Venom', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Darth Vader', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Yoda', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Luke Skywalker', 'category_id' => CharacterCategory::FICTION],

            // Ficção — animação
            ['name' => 'Pato Donald', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Perna Longa', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Pernalonga', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Patolino', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Scooby-Doo', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Patrick Estrela', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Pica-Pau', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Popeye', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Shrek', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Burro', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Simba', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Elsa', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Moana', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Mulan', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Cinderela', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Branca de Neve', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Aladdin', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Gênio', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Buzz Lightyear', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Woody', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Nemo', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Stitch', 'category_id' => CharacterCategory::FICTION],

            // Ficção — anime
            ['name' => 'Sasuke Uchiha', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Goku', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Vegeta', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Luffy', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Pikachu', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Ash Ketchum', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Sailor Moon', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Totoro', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Levi Ackerman', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Light Yagami', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Edward Elric', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Kirito', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Saitama', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Deku', 'category_id' => CharacterCategory::FICTION],

            // Ficção — turma da Mônica / personagens BR
            ['name' => 'Cascão', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Magali', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Chico Bento', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Benji', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Chapolin Colorado', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Tio Barnabé', 'category_id' => CharacterCategory::FICTION],

            // Ficção — games
            ['name' => 'Mario', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Luigi', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Sonic', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Kirby', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Link', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Crash Bandicoot', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Lara Croft', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Master Chief', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Kratos', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Pac-Man', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Donkey Kong', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Steve', 'category_id' => CharacterCategory::FICTION],

            // Ficção — live-action
            ['name' => 'Hermione Granger', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Voldemort', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'James Bond', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Indiana Jones', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Forrest Gump', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Jack Sparrow', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Rocky Balboa', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Terminator', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Neo', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Gandalf', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Frodo', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Jon Snow', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Walter White', 'category_id' => CharacterCategory::FICTION],

            ['name' => 'Quico', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Dona Florinda', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Professor Girafales', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Chiquinha', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Seu Barriga', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Dumbledore', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Snape', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Rony Weasley', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Hagrid', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Draco Malfoy', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Dobby', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Sirius Black', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Aragorn', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Legolas', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Gimli', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Gollum', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Sauron', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Bilbo', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Sam', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Han Solo', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Princesa Leia', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Chewbacca', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Obi-Wan Kenobi', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Grogu', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Papa-Léguas', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Coiote', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'R2-D2', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'C-3PO', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Kylo Ren', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Frajola', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Piu-Piu', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Taz', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Bart Simpson', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Lisa Simpson', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Marge Simpson', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Drácula', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Pennywise', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Sherlock Holmes', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Loki', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Doutor Estranho', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Arlequina', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Lex Luthor', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Scar', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Maleficent', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Seiya', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Piccolo', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Kakashi', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Zoro', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Princesa Peach', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Bowser', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Emília', 'category_id' => CharacterCategory::FICTION],
            ['name' => 'Saci-Pererê', 'category_id' => CharacterCategory::FICTION],

            // Arte
            ['name' => 'Wagner Moura', 'category_id' => CharacterCategory::ART],
            ['name' => 'Lázaro Ramos', 'category_id' => CharacterCategory::ART],
            ['name' => 'Tony Ramos', 'category_id' => CharacterCategory::ART],
            ['name' => 'Rodrigo Santoro', 'category_id' => CharacterCategory::ART],
            ['name' => 'Fernanda Montenegro', 'category_id' => CharacterCategory::ART],
            ['name' => 'Taís Araújo', 'category_id' => CharacterCategory::ART],
            ['name' => 'Camila Pitanga', 'category_id' => CharacterCategory::ART],
            ['name' => 'Regina Casé', 'category_id' => CharacterCategory::ART],
            ['name' => 'Roberto Carlos', 'category_id' => CharacterCategory::ART],
            ['name' => 'Caetano Veloso', 'category_id' => CharacterCategory::ART],
            ['name' => 'Gilberto Gil', 'category_id' => CharacterCategory::ART],
            ['name' => 'Zeca Pagodinho', 'category_id' => CharacterCategory::ART],
            ['name' => 'Michael Jackson', 'category_id' => CharacterCategory::ART],
            ['name' => 'Anitta', 'category_id' => CharacterCategory::ART],
            ['name' => 'Elis Regina', 'category_id' => CharacterCategory::ART],
            ['name' => 'Marília Mendonça', 'category_id' => CharacterCategory::ART],
            ['name' => 'Ivete Sangalo', 'category_id' => CharacterCategory::ART],
            ['name' => 'Tom Jobim', 'category_id' => CharacterCategory::ART],
            ['name' => 'Raul Seixas', 'category_id' => CharacterCategory::ART],
            ['name' => 'Cazuza', 'category_id' => CharacterCategory::ART],
            ['name' => 'Rita Lee', 'category_id' => CharacterCategory::ART],
            ['name' => 'Gal Costa', 'category_id' => CharacterCategory::ART],
            ['name' => 'Tim Maia', 'category_id' => CharacterCategory::ART],
            ['name' => 'Djavan', 'category_id' => CharacterCategory::ART],
            ['name' => 'Ludmilla', 'category_id' => CharacterCategory::ART],
            ['name' => 'Prince', 'category_id' => CharacterCategory::ART],
            ['name' => 'David Bowie', 'category_id' => CharacterCategory::ART],
            ['name' => 'Freddie Mercury', 'category_id' => CharacterCategory::ART],
            ['name' => 'Beyoncé', 'category_id' => CharacterCategory::ART],
            ['name' => 'Taylor Swift', 'category_id' => CharacterCategory::ART],
            ['name' => 'Madonna', 'category_id' => CharacterCategory::ART],
            ['name' => 'Rihanna', 'category_id' => CharacterCategory::ART],
            ['name' => 'Billie Eilish', 'category_id' => CharacterCategory::ART],
            ['name' => 'Ariana Grande', 'category_id' => CharacterCategory::ART],
            ['name' => 'Chico Buarque', 'category_id' => CharacterCategory::ART],
            ['name' => 'Fernando Meirelles', 'category_id' => CharacterCategory::ART],
            ['name' => 'Walter Salles', 'category_id' => CharacterCategory::ART],
            ['name' => 'Steven Spielberg', 'category_id' => CharacterCategory::ART],
            ['name' => 'Chico Anysio', 'category_id' => CharacterCategory::ART],
            ['name' => 'Renato Aragão', 'category_id' => CharacterCategory::ART],
            ['name' => 'Tirullipa', 'category_id' => CharacterCategory::ART],
            ['name' => 'Fábio Porchat', 'category_id' => CharacterCategory::ART],
            ['name' => 'Sócrates', 'category_id' => CharacterCategory::ART],
            ['name' => 'Platão', 'category_id' => CharacterCategory::ART],
            ['name' => 'Friedrich Nietzsche', 'category_id' => CharacterCategory::ART],
            ['name' => 'Machado de Assis', 'category_id' => CharacterCategory::ART],
            ['name' => 'Jorge Amado', 'category_id' => CharacterCategory::ART],
            ['name' => 'Clarice Lispector', 'category_id' => CharacterCategory::ART],
            ['name' => 'Paulo Coelho', 'category_id' => CharacterCategory::ART],
            ['name' => 'Carlos Drummond de Andrade', 'category_id' => CharacterCategory::ART],
            ['name' => 'Vinicius de Moraes', 'category_id' => CharacterCategory::ART],
            ['name' => 'Cecília Meireles', 'category_id' => CharacterCategory::ART],
            ['name' => 'Tarsila do Amaral', 'category_id' => CharacterCategory::ART],
            ['name' => 'Cândido Portinari', 'category_id' => CharacterCategory::ART],
            ['name' => 'Pablo Picasso', 'category_id' => CharacterCategory::ART],
            ['name' => 'Aleijadinho', 'category_id' => CharacterCategory::ART],
            ['name' => 'Victor Brecheret', 'category_id' => CharacterCategory::ART],
            ['name' => 'Sebastião Salgado', 'category_id' => CharacterCategory::ART],
            ['name' => 'Alok', 'category_id' => CharacterCategory::ART],
            ['name' => 'Vintage Culture', 'category_id' => CharacterCategory::ART],
            ['name' => 'Gisele Bündchen', 'category_id' => CharacterCategory::ART],
            ['name' => 'Adriana Lima', 'category_id' => CharacterCategory::ART],
            ['name' => 'Oskar Metsavaht', 'category_id' => CharacterCategory::ART],
            ['name' => 'David Copperfield', 'category_id' => CharacterCategory::ART],
            ['name' => 'Carlinhos de Jesus', 'category_id' => CharacterCategory::ART],
            ['name' => 'Alan Turing', 'category_id' => CharacterCategory::SCIENCE_AND_TECHNOLOGY],
            ['name' => 'Bob Dylan', 'category_id' => CharacterCategory::ART],
            ['name' => 'PinkPantheress', 'category_id' => CharacterCategory::ART],
            ['name' => 'Joan Baez', 'category_id' => CharacterCategory::ART],
            ['name' => 'Kate Bush', 'category_id' => CharacterCategory::ART],
            ['name' => 'Frank Ocean', 'category_id' => CharacterCategory::ART],
            ['name' => 'Robert Smith', 'category_id' => CharacterCategory::ART],
            ['name' => 'Thom Yorke', 'category_id' => CharacterCategory::ART],
            ['name' => 'Grimes', 'category_id' => CharacterCategory::ART],
            ['name' => 'Björk', 'category_id' => CharacterCategory::ART],
            ['name' => 'Lana Del Rey', 'category_id' => CharacterCategory::ART],
            ['name' => 'Kurt Cobain', 'category_id' => CharacterCategory::ART],
            ['name' => 'Gerard Way', 'category_id' => CharacterCategory::ART],
            ['name' => 'Cleópatra', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Che Guevara', 'category_id' => CharacterCategory::POLITICS_AND_MILITARY],
            ['name' => 'Olavo de Carvalho', 'category_id' => CharacterCategory::ART],
        ];

        foreach ($characters as $character) {
            DB::table('characters')->updateOrInsert([
                'name' => $character['name'],
            ], [
                'picture' => '',
                'category_id' => $character['category_id']->value,
            ]);
        }
    }
}
