services:
  front:
    build:
      context: ./front
      dockerfile: .docker/local/Dockerfile
    image: apolo-guesses-front
    container_name: apolo-guesses-front
    entrypoint: /app/.docker/local/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
      - /app/node_modules

  back:
    build:
      context: ./back
      dockerfile: .docker/local/Dockerfile
    image: apolo-guesses-back
    container_name: apolo-guesses-back
    entrypoint: /app/.docker/local/entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - ./back:/app
      - /app/vendor
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: apolo
      DB_USERNAME: apolo
      DB_PASSWORD: apolo
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16-alpine
    container_name: apolo-guesses-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: apolo
      POSTGRES_USER: apolo
      POSTGRES_PASSWORD: apolo
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apolo"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database-data: